# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  projectSrc: 'src/todo.csproj'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectSrc)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(projectSrc)'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Jason Specland MS Internal(78665f33-bc7d-43df-9f83-ac1064dd74eb)'
    appType: 'webApp'
    WebAppName: 'private-link-demo-web-jaspecla'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
